
/**
 * Project schema
 */

import {Schema} from 'mongoose';
import statuses from './statuses';

export default {
  'title':        { type: String, required: true },
  'domain':       String,
  'description':  { type: String },

  'money': { type: Number, required: true },
  'desc': { type: String, required: true },
  'motivation': { type: String, required: true },
  'existed': { type: String, required: true },
  'problem': { type: String, required: true },
  'solution': { type: String, required: true },
  'why': { type: String, required: true },
  'ta': { type: String, required: true },
  'growth': { type: String, required: true },
  'similar': { type: String, required: true },
  'refdesign': { type: String, required: true },
  'pastprj': { type: String, required: true },
  'cowork': { type: String, required: true },
  'usetime': { type: String, required: true },
  'spending': { type: String, required: true },
  'feedback': { type: String, required: true },
  'product': { type: String, required: true },
  'milestone1': { type: String, required: true },
  'milestone2': { type: String, required: true },
  'difficulty': { type: String, required: true },
  'future': { type: String, required: true },
  'otherfund': { type: String, required: true },
  'category': { type: String, required: true },
  'slide': { type: String },
  'related': { type: String, required: true },
  'nonos': { type: String, required: true },
  'role': { type: String, required: true },
  'detailUser': { type: String, required: true},
  'detailProblem': { type: String, required: true},
  'detailService': { type: String, required: true},
  'detailSolution': { type: String, required: true},
  'detailCompetitor': { type: String, required: true},
  'detailCompare': { type: String, required: true},

  'revisions': { type: [{
    description: String,
    money: Number,
    desc: String,
    motivation: String,
    existed: String,
    problem: String,
    solution: String,
    why: String,
    ta: String,
    growth: String,
    similar: String,
    refdesign: String,
    pastprj: String,
    cowork: String,
    usetime: String,
    spending: String,
    feedback: String,
    product: String,
    milestone1: String,
    milestone2: String,
    difficulty: String,
    future: String,
    otherfund: String,
    category: String,
    slide: String,
    related: String,
    nonos: String,
    role: String,
    detailUser: String,
    detailProblem: String,
    detailService: String,
    detailSolution: String,
    detailCompetitor: String,
    detailCompare: String,
    timestamp: Date
  }], select: false },

  'leader':       { type: Schema.ObjectId, required: true, ref: 'User' },
  'status':       { type: String, enum: statuses, default: statuses[0] },
  'contributors': [{ type: Schema.ObjectId, ref: 'User'}],
  'followers':    [{ type: Schema.ObjectId, ref: 'User'}],
  'awarded':      { type: Boolean, default: false },
  'finalist':     { type: Boolean, default: false },
  'cover':        String,
  'link':         String,
  'tags':         [String],
  'updated_at':   { type: Date, default: Date.now },
  'created_at':   { type: Date, default: Date.now }
};
